name: Swift

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:    
  test:
    name: Test
    runs-on: macos-latest

    steps:
    - name: Bundle Install
      run: bundle install
    - name: Unit tests
      run: bundle exec fastlane tests
